services:
  mongodb:
    image: mongo:latest
    container_name: solvibe_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: solvibe
    restart: unless-stopped

volumes:
  mongo_data: